StudentRegistrationBureauMVC/Controllers/EnrollmentsController.cs
using ApplicationService.Implementations;
using Data.Entities;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using NuGet.Configuration;
using StudentRegistrationBureauMVC.Models.IndexVMs;
using StudentRegistrationBureauMVC.Models;
using System.Net.NetworkInformation;
using System.Xml.Linq;
using StudentRegistrationBureauMVC.Models.Shared;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudentRegistrationBureauMVC.ActionFilters;
using Microsoft.EntityFrameworkCore;

public class EnrollmentsController : Controller
{
    private readonly EnrollmentManagementService _enrollmentService;
    private readonly CourseManagementService _courseService;
    private readonly StudentManagementService _studentService;

    public EnrollmentsController(EnrollmentManagementService enrollmentService, CourseManagementService courseService, StudentManagementService studentService)
    {
        _enrollmentService = enrollmentService;
        _courseService = courseService;
        _studentService = studentService;
    }

    // GET: Students
    public IActionResult Index(EnrollmentIndexVM model)
    {
        IEnumerable<Enrollment> enrollments = _enrollmentService.Get(model.Pager.Page, model.Pager.ItemsPerPage, model.Filter);
        model.Enrollments = enrollments.Select(enrollment => new EnrollmentVM(enrollment));
        model.Pager.PagesCount = _enrollmentService.GetPageCount(model.Pager.ItemsPerPage, model.Filter);

        List<Course> courses = _courseService.Get(1, int.MaxValue).ToList();
        courses.Insert(0, new Course() { Id = 0, Name = string.Empty });
        ViewData["Courses"] = new SelectList(courses, "Name", "Name", model.Filter.Course);

        return View(model);
    }

    // GET: Enrollment/Delete/5
    [Authenticated]
    public IActionResult Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var enrollment = _enrollmentService.GetById(id.Value);
        if (enrollment == null)
        {
           return NotFound();
        }

        var viewModel = new EnrollmentVM(enrollment);
        return View(viewModel);
    }

    // POST: Students/Delete/5
    [HttpPost, ActionName("Delete")]
    [Authenticated]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteConfirmed(int id)
    {
        var enrollment = _enrollmentService.GetById(id);
        if (enrollment != null)
        {
            bool isSuccessful = _enrollmentService.Delete(id);
            if (!isSuccessful)
            {
                ViewData["ErrorMessage"] =
                    "Failed to delete enrollment!";
                return View(new EnrollmentVM(enrollment));
            }
        }

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var enrollment = _enrollmentService.GetById(id.Value);
        if (enrollment == null)
        {
            return NotFound();
        }

        return View(new EnrollmentVM(enrollment));
    }

    [Authenticated]
    public IActionResult Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var enrollment = _enrollmentService.GetById(id.Value);
        if (enrollment == null)
        {
            return NotFound();
        }
        //Getting all faculties and majors for making drop-down lists
        return View(new EnrollmentVM(enrollment));
    }

    [HttpPost]
    [Authenticated]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(int id, EnrollmentVM enrollmentVM)
    {
        if (id != enrollmentVM.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                Enrollment editedEnrollment = enrollmentVM.ToEntity();
                bool isSuccessful = _enrollmentService.Save(editedEnrollment);
                if (isSuccessful)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_enrollmentService.Exists(enrollmentVM.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            ViewData["ErrorMessage"] =
                "Failed to edit enrollment!";
        }

        return View(enrollmentVM);
    }

    [Authenticated]
    public IActionResult Create()
    {
        // Getting all faculties and majors for making drop-down lists
        ViewData["StudentId"] = new SelectList(_studentService.Get(1, int.MaxValue)
         .Select(s => new SelectListItem { Value = s.Id.ToString(), Text = $"{s.FirstName} {s.MiddleName} {s.LastName} - {s.FacultyNumber}" }), "Value", "Text");

        ViewData["CourseId"] = new SelectList(_courseService.Get(1, int.MaxValue), "Id", "Name");
        return View();
    }

    // POST: Students/Create
    [HttpPost]
    [Authenticated]
    [ValidateAntiForgeryToken]
    public IActionResult Create(EnrollmentVM enrollmentVM)
    {
        if (ModelState.IsValid)
        {
            Enrollment createdEnrollment = enrollmentVM.ToEntity();
            createdEnrollment.Id = 0;
            bool isSuccessful = _enrollmentService.Save(createdEnrollment);
            if (isSuccessful)
            {
                return RedirectToAction(nameof(Index));
            }

            ViewData["ErrorMessage"] =
                "Failed to create enrollment! The student is already enrolled in the specified Course.";
        }

        // Getting all faculties and majors for making drop-down lists
        ViewData["StudentId"] = new SelectList(_studentService.Get(1, int.MaxValue)
         .Select(s => new SelectListItem { Value = s.Id.ToString(), Text = $"{s.FirstName} {s.MiddleName} {s.LastName} - {s.FacultyNumber}" }), "Value", "Text");

        ViewData["CourseId"] = new SelectList(_courseService.Get(1, int.MaxValue), "Id", "Name");
        return View(enrollmentVM);
    }
}

StudentRegistrationBureauMVC/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Context;
using Data.Entities;
using ApplicationService.Implementations;
using StudentRegistrationBureauMVC.Models.IndexVMs;
using StudentRegistrationBureauMVC.Models;
using Microsoft.AspNetCore.Authorization;
using StudentRegistrationBureauMVC.ActionFilters;
using OfficeOpenXml;
using OfficeOpenXml.FormulaParsing.Excel.Functions.RefAndLookup;
using System.Diagnostics;

namespace StudentRegistrationBureauMVC.Controllers
{
    public class StudentsController : Controller
    {
        private readonly StudentManagementService _studentService;
        private readonly MajorManagementService _majorService;
        private readonly FacultyManagementService _facultyService;

        public StudentsController(StudentManagementService studentService,
            MajorManagementService majorService, FacultyManagementService facultyService)
        {
            _studentService = studentService;
            _majorService = majorService;
            _facultyService = facultyService;
        }

        // GET: Students
        public IActionResult Index(StudentIndexVM model)
        {
            IEnumerable<Student> students = _studentService.Get(model.Pager.Page, model.Pager.ItemsPerPage, model.Filter);
            model.Students = students.Select(student => new StudentVM(student));
            model.Pager.PagesCount = _studentService.GetPageCount(model.Pager.ItemsPerPage, model.Filter);

            /*Getting all faculties and majors for making drop-down lists which will be used for filtering.
              The newly inserted elements are default values which indicate that no filter is being applied.*/
            List<Faculty> faculties = _facultyService.Get(1, int.MaxValue).ToList();
            faculties.Insert(0, new Faculty() { Id = 0, Name = "-" });
            List<Major> majors = _majorService.Get(1, int.MaxValue).ToList();
            majors.Insert(0, new Major() { Id = 0, Name = "-" });
            ViewData["Faculties"] = new SelectList(faculties, "Id", "Name", model.Filter.FacultyId);
            ViewData["Majors"] = new SelectList(majors, "Id", "Name", model.Filter.MajorId);

            return View(model);
        }

        // GET: Students/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = _studentService.GetById(id.Value);
            if (student == null)
            {
                return NotFound();
            }

            return View(new StudentVM(student));
        }

        // GET: Students/Create
        [Authenticated]

        public IActionResult Create()
        {
            //Getting all faculties and majors for making drop-down lists
            ViewData["FacultyId"] = new SelectList(_facultyService.Get(1, int.MaxValue), "Id", "Name");
            ViewData["MajorId"] = new SelectList(_majorService.Get(1, int.MaxValue), "Id", "Name");
            return View();
        }

        // POST: Students/Create
        [HttpPost]
        [Authenticated]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StudentVM studentVM)
        {
            if (ModelState.IsValid)
            {
                Student createdStudent = studentVM.ToEntity();
                createdStudent.Id = 0;
                bool isSuccessful = _studentService.Save(createdStudent);
                if (isSuccessful)
                {
                    return RedirectToAction(nameof(Index));
                }

                ViewData["ErrorMessage"] = 
                    "Failed to create student! Ensure that the faculty number is unique and try again.";
            }
            //Getting all faculties and majors for making drop-down lists
            ViewData["FacultyId"] = new SelectList(_facultyService.Get(1, int.MaxValue), "Id", "Name", studentVM.FacultyId);
            ViewData["MajorId"] = new SelectList(_majorService.Get(1, int.MaxValue), "Id", "Name", studentVM.MajorId);
            return View(studentVM);
        }

        // GET: Students/Edit/5
        [Authenticated]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = _studentService.GetById(id.Value);
            if (student == null)
            {
                return NotFound();
            }
            //Getting all faculties and majors for making drop-down lists
            ViewData["FacultyId"] = new SelectList(_facultyService.Get(1, int.MaxValue), "Id", "Name", student.FacultyId);
            ViewData["MajorId"] = new SelectList(_majorService.Get(1, int.MaxValue), "Id", "Name", student.MajorId);
            return View(new StudentVM(student));
        }

        // POST: Students/Edit/5
        [HttpPost]
        [Authenticated]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, StudentVM studentVM)
        {
            if (id != studentVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Student editedStudent = studentVM.ToEntity();
                    bool isSuccessful = _studentService.Save(editedStudent);
                    if (isSuccessful)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_studentService.Exists(studentVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewData["ErrorMessage"] =
                    "Failed to edit student! Ensure that the faculty number is unique and try again.";
            }
            //Getting all faculties and majors for making drop-down lists
            ViewData["FacultyId"] = new SelectList(_facultyService.Get(1, int.MaxValue), "Id", "Name", studentVM.FacultyId);
            ViewData["MajorId"] = new SelectList(_majorService.Get(1, int.MaxValue), "Id", "Name", studentVM.MajorId);
            return View(studentVM);
        }

        // GET: Students/Delete/5
        [Authenticated]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = _studentService.GetById(id.Value);
            if (student == null)
            {
                return NotFound();
            }

            return View(new StudentVM(student));
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authenticated]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var student = _studentService.GetById(id);
            if (student != null)
            {
                bool isSuccessful = _studentService.Delete(id);
                if(!isSuccessful) 
                {
                    ViewData["ErrorMessage"] = 
                        "Failed to delete student! Ensure that the student has no enrollments and try again.";
                    return View(new StudentVM(student));
                }
            }

            return RedirectToAction(nameof(Index));
        }


        [Authenticated]
        public IActionResult ExportAllStudents()
        {
            StudentIndexVM model = new StudentIndexVM();

            model.Pager.ItemsPerPage = int.MaxValue;

            List<Student> students = _studentService.Get(model.Pager.Page, model.Pager.ItemsPerPage, model.Filter).ToList();


            var stream = new MemoryStream();

            using(var xlPackage = new ExcelPackage(stream))
            {
                var worksheet = xlPackage.Workbook.Worksheets.Add("Students");

                worksheet.Cells["A1"].Value = "First Name";
                worksheet.Cells["B1"].Value = "Middle Name";
                worksheet.Cells["C1"].Value = "Last Name";
                worksheet.Cells["D1"].Value = "Faculty number";
                worksheet.Cells["E1"].Value = "Faculty";
                worksheet.Cells["F1"].Value = "Major";
                worksheet.Cells["G1"].Value = "FacultyId";
                worksheet.Cells["H1"].Value = "MajorId";


                var row = 2;
                foreach(var student in students)
                {

                    worksheet.Cells[row, 1].Value = student.FirstName;
                    worksheet.Cells[row, 2].Value = student.MiddleName;
                    worksheet.Cells[row, 3].Value = student.LastName;
                    worksheet.Cells[row, 4].Value = student.FacultyNumber;
                    worksheet.Cells[row, 5].Value = student.Faculty.Name;
                    worksheet.Cells[row, 6].Value = student.Major.Name;
                    worksheet.Cells[row, 7].Value = student.FacultyId;
                    worksheet.Cells[row, 8].Value = student.MajorId;

                    row++;
                }

                xlPackage.Workbook.Properties.Title = "Student List";
                xlPackage.Workbook.Properties.Author = HttpContext.User.Identity!.Name;

                xlPackage.Save();

            }

            stream.Position = 0;

            return File(stream,"application/vnd.openxmlformats-officedocument.spreadsheethml.sheet", "students.xlsx");
        }

        [HttpGet]
        [Authenticated]
        public IActionResult ImportStudents()
        {
            return View();
        }

        [HttpPost]
        [Authenticated]
        [ValidateAntiForgeryToken]

StudentRegistrationBureauMVC/Views/Students/Create.cshtml
@model StudentRegistrationBureauMVC.Models.StudentVM

@{
    ViewData["Title"] = "Create Student";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />

@if (ViewData["ErrorMessage"] != null)
{
    <h4 class="text-danger">@ViewData["ErrorMessage"]</h4>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FacultyNumber" class="control-label"></label>
                <input asp-for="FacultyNumber" class="form-control" />
                <span asp-validation-for="FacultyNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FacultyId" class="control-label"></label>
                <select asp-for="FacultyId" class ="form-control" asp-items="ViewBag.FacultyId"></select>
            </div>
            <div class="form-group">
                <label asp-for="MajorId" class="control-label"></label>
                <select asp-for="MajorId" class ="form-control" asp-items="ViewBag.MajorId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudentRegistrationBureauMVC/Views/Students/Delete.cshtml
@model StudentRegistrationBureauMVC.Models.StudentVM

@{
    ViewData["Title"] = "Delete Student";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />

    @if (ViewData["ErrorMessage"] != null)
    {
        <h4 class="text-danger">@ViewData["ErrorMessage"]</h4>
    }

    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacultyNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FacultyNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Faculty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Faculty!.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Major)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Major!.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

StudentRegistrationBureauMVC/Views/Students/Details.cshtml
@model StudentRegistrationBureauMVC.Models.StudentVM

@{
    ViewData["Title"] = "Student Details";
}

<div>
    <h4>Student Details</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacultyNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FacultyNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FacultyId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Faculty!.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MajorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Major!.Name)
        </dd>
        <a asp-action="Index" asp-controller="Enrollments" asp-route-Filter.FacultyNumber="@Model?.FacultyNumber">See grades</a>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

StudentRegistrationBureauMVC/Views/Students/Edit.cshtml
@model StudentRegistrationBureauMVC.Models.StudentVM

@{
    ViewData["Title"] = "Edit Student";
}

<h1>Edit</h1>

<h4>Student</h4>
<hr />

@if (ViewData["ErrorMessage"] != null)
{
    <h4 class="text-danger">@ViewData["ErrorMessage"]</h4>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FacultyNumber" class="control-label"></label>
                <input asp-for="FacultyNumber" class="form-control" />
                <span asp-validation-for="FacultyNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FacultyId" class="control-label"></label>
                <select asp-for="FacultyId" class="form-control" asp-items="ViewBag.FacultyId"></select>
                <span asp-validation-for="FacultyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MajorId" class="control-label"></label>
                <select asp-for="MajorId" class="form-control" asp-items="ViewBag.MajorId"></select>
                <span asp-validation-for="MajorId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudentRegistrationBureauMVC/Views/Students/ImportStudents.cshtml
@{
    ViewData["Title"] = "ImportStudents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Import students</h1>

<form asp-action="ImportStudents" asp-controller="Students" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label>Import Excel file with student data</label>
        <input id="batchStudents" name="batchStudents" class="form-control" type="file" />
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Import</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

StudentRegistrationBureauMVC/Views/Students/Index.cshtml
@model StudentRegistrationBureauMVC.Models.IndexVMs.StudentIndexVM

@{
    ViewData["Title"] = "Students";
}

@{
    ViewData["FacultyId"] = Model.Filter.FacultyId;
    ViewData["MajorId"] = Model.Filter.MajorId;
    ViewData["FacultyNumber"] = Model.Filter.FacultyNumber;
}

<h1>Students</h1>

<hr />




<div class="mb-2">
    <h4>Filtering options</h4>
    <form method="get" class="d-inline-block mb-1">
        <input type="hidden" name="Pager.ItemsPerPage" value="@Model.Pager.ItemsPerPage" />
        <div class="form-group">
            <label asp-for="Filter.FacultyId" class="control-label"></label>
            <select asp-for="Filter.FacultyId" class="form-control" asp-items="ViewBag.Faculties"></select>
        </div>
        <div class="form-group">
            <label asp-for="Filter.MajorId" class="control-label"></label>
            <select asp-for="Filter.MajorId" class="form-control" asp-items="ViewBag.Majors"></select>
        </div>
        <div class="form-group">
            <label asp-for="Filter.FacultyNumber" class="control-label"></label>
            <input asp-for="Filter.FacultyNumber" class="form-control" value="@Model.Filter.FacultyNumber" />
        </div>
        <div class="form-group d-flex gap-5">
            <input type="submit" class="btn btn-primary" value="Filter" />
            <a asp-action="Index" asp-route-Pager.ItemsPerPage="@Model.Pager.ItemsPerPage">
                <!button type="button" class="btn btn-light border-dark">Clear filter</!button>
            </a>
        </div>
    </form>
</div>

@{
    await Html.RenderPartialAsync("/Views/Partial/StudentPagerPartial.cshtml", Model.Pager, ViewData);
}

<div class="d-flex gap-5">
    <a asp-action="ExportAllStudents" asp-controller="Students" class="btn text-light bg-medium-sapphire mb-3">Export All Students</a>
    <a asp-action="ImportStudents" asp-controller="Students" class="btn text-light bg-medium-sapphire mb-3">Import</a>
</div>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameForInnerType((StudentVM s) => s.FullName)
            </th>
            <th>
                @Html.DisplayNameForInnerType((StudentVM s) => s.FacultyNumber)
            </th>
            <th>
                @Html.DisplayNameForInnerType((StudentVM s) => s.FacultyId)
            </th>
            <th>
                @Html.DisplayNameForInnerType((StudentVM s) => s.MajorId)
            </th>
            <th></th>
        </tr>
    </thead>
  <tbody>
    @foreach (var item in Model.Students!) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FacultyNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Faculty!.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Major!.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
  </tbody>
</table>