StudentRegistrationBureauMVC/Models/Shared/PagerVM.cs
namespace StudentRegistrationBureauMVC.Models.Shared
{
    public class PagerVM
    {
        public int Page { get; set; } = 1;
        public int ItemsPerPage { get; set; } = 10;
        public int PagesCount { get; set; }
    }
}

StudentRegistrationBureauMVC/Controllers/AuthController.cs
using Data.Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StudentRegistrationBureauMVC.ActionFilters;
using StudentRegistrationBureauMVC.Models.IdentityVMs;

namespace StudentRegistrationBureauMVC.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public AuthController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        [Anonymous]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [Anonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterVM model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser { UserName = model.Email, Email = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("index", "home");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        [Anonymous]
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        [Anonymous]
        public async Task<IActionResult> LogIn(LogInVM model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);
                if (user == null)
                {
                    ModelState.AddModelError(string.Empty, "Wrong password or email, try again!");
                    return View(model);
                }

                var result = await _signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, lockoutOnFailure: false);

                if (result.Succeeded)
                {
                    return RedirectToAction("index", "home");
                }

                ModelState.AddModelError(string.Empty, "Wrong password or email, try again!");
            }

            return View(model);
        }

        [Authenticated]
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("index", "home");
        }

        public IActionResult UnauthenticatedError()
        {
            ViewBag.ErrorMessage = "You have to log in to use this action!";
            return View();
        }
    }
}

StudentRegistrationBureauMVC/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Context;
using Data.Entities;
using ApplicationService.Implementations;
using StudentRegistrationBureauMVC.Models.IndexVMs;
using StudentRegistrationBureauMVC.Models;
using StudentRegistrationBureauMVC.ActionFilters;

namespace StudentRegistrationBureauMVC.Controllers
{
    public class CoursesController : Controller
    {
        private readonly CourseManagementService _courseService;
        public CoursesController(CourseManagementService courseService)
        {
            _courseService = courseService;
        }

        // GET: Courses
        public IActionResult Index(CourseIndexVM model)
        {
            IEnumerable<Course> courses = _courseService.Get(model.Pager.Page, model.Pager.ItemsPerPage);
            model.Courses = courses.Select(course => new CourseVM(course));
            model.Pager.PagesCount = _courseService.GetPageCount(model.Pager.ItemsPerPage);
            return View(model);
        }

        // GET: Courses/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = _courseService.GetById(id.Value);
            if (course == null)
            {
                return NotFound();
            }

            return View(new CourseVM(course));
        }

        // GET: Courses/Create
        [Authenticated]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
       
        [HttpPost]
        [Authenticated]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CourseVM courseVM)
        {
            if (ModelState.IsValid)
            {
                Course createdCourse = courseVM.ToEntity();
                createdCourse.Id = 0;
                bool isSuccessful = _courseService.Save(createdCourse);
                if (isSuccessful)
                {
                    return RedirectToAction(nameof(Index));
                }

                ViewData["ErrorMessage"] =
                    "Failed to create course! Ensure that the course is unique and try again.";
            }
            return View(courseVM);
        }

        // GET: Courses/Edit/5

        [HttpGet]
        [Authenticated]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = _courseService.GetById(id.Value);
            if (course == null)
            {
                return NotFound();
            }
            return View(new CourseVM(course));
        }

        // POST: Courses/Edit/5
        [HttpPost]
        [Authenticated]
        public IActionResult Edit(int id, CourseVM courseVM)
        {
            if (id != courseVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Course editedCourse = courseVM.ToEntity();
                    bool isSuccessful = _courseService.Save(editedCourse);
                    if (isSuccessful)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_courseService.Exists(courseVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewData["ErrorMessage"] =
                    "Failed to edit course! Ensure that the course is unique and try again.";
            }
            return View(courseVM);
        }

        // GET: Courses/Delete/5
        [Authenticated]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = _courseService.GetById(id.Value);
            if (course == null)
            {
                return NotFound();
            }

            return View(new CourseVM(course));
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authenticated]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var course = _courseService.GetById(id);
            if (course != null)
            {
                bool isSuccessful = _courseService.Delete(id);
                if (!isSuccessful)
                {
                    ViewData["ErrorMessage"] =
                        "Failed to delete course! Ensure that the course has no enrollments and try again.";
                    return View(new CourseVM(course));
                }
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

StudentRegistrationBureauMVC/Controllers/MajorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Context;
using Data.Entities;
using ApplicationService.Implementations;
using StudentRegistrationBureauMVC.Models.IndexVMs;
using StudentRegistrationBureauMVC.Models;
using StudentRegistrationBureauMVC.ActionFilters;

namespace StudentRegistrationBureauMVC.Controllers
{
    public class MajorsController : Controller
    {
        private readonly MajorManagementService _majorService;

        public MajorsController(MajorManagementService majorService)
        {
            _majorService = majorService;
        }

        // GET: Majors
        public IActionResult Index(MajorIndexVM model)
        {
            IEnumerable<Major> majors = _majorService.Get(model.Pager.Page, model.Pager.ItemsPerPage);
            model.Majors = majors.Select(major => new MajorVM(major));
            model.Pager.PagesCount = _majorService.GetPageCount(model.Pager.ItemsPerPage);
            return View(model);
        }

        // GET: Majors/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var major = _majorService.GetById(id.Value);
            if (major == null)
            {
                return NotFound();
            }

            return View(new MajorVM(major));
        }

        // GET: Majors/Create
        [Authenticated]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Majors/Create
        [HttpPost]
        [Authenticated]
        [ValidateAntiForgeryToken]
        public IActionResult Create(MajorVM majorVM)
        {
            if (ModelState.IsValid)
            {
                Major createdMajor = majorVM.ToEntity();
                createdMajor.Id = 0;
                bool isSuccessful = _majorService.Save(createdMajor);
                if (isSuccessful)
                {
                    return RedirectToAction(nameof(Index));
                }

                ViewData["ErrorMessage"] =
                    "Failed to create major! Ensure that the major is unique and try again.";
            }
            return View(majorVM);
        }

        // GET: Majors/Edit/5
        [Authenticated]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var major = _majorService.GetById(id.Value);
            if (major == null)
            {
                return NotFound();
            }
            return View(new MajorVM(major));
        }

        // POST: Majors/Edit/5
        [HttpPost]
        [Authenticated]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, MajorVM majorVM)
        {
            if (id != majorVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Major editedMajor = majorVM.ToEntity();
                    bool isSuccessful = _majorService.Save(editedMajor);
                    if (isSuccessful)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_majorService.Exists(majorVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewData["ErrorMessage"] =
                    "Failed to edit major! Ensure that the major is unique and try again.";
            }
            return View(majorVM);
        }

        // GET: Majors/Delete/5
        [Authenticated]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var major = _majorService.GetById(id.Value);
            if (major == null)
            {
                return NotFound();
            }

            return View(new MajorVM(major));
        }

        // POST: Majors/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authenticated]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var major = _majorService.GetById(id);
            if (major != null)
            {
                bool isSuccessful = _majorService.Delete(id);
                if (!isSuccessful)
                {
                    ViewData["ErrorMessage"] = 
                        "Failed to delete major! Ensure that the major has no students and try again.";
                    return View(new MajorVM(major));
                }
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

StudentRegistrationBureauMVC/Views/Shared/_Layout.cshtml
@using Data.Context
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Student Registration Bureau</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/srb-styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentRegistrationBureauMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student Registration Bureau</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Majors" asp-action="Index">Majors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculties" asp-action="Index">Faculties</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrollments" asp-action="Index">Enrollments</a>
                        </li>
                    </ul>
                </div>
            </div>
            <ul class="navbar-nav flex-grow-1">
                @if (SignInManager.IsSignedIn(User))
                {
                    <li>
                        <a class="nav-link text-dark">Hello @User.Identity!.Name!</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="LogOut">Sign Out</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="LogIn">Login</a>
                    </li>
                }
            </ul>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Student Registration Bureau - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>